trigger:
- master

resources:
  repositories:
    - repository: self
      type: git

jobs:
- job: Deploy
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
    demands:
    - msbuild
    - visualstudio

  steps:
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: 'Azure-Fogo-Connection'
      appName: 'Fogolocationfunctionappdatapull'
      package: '$(System.DefaultWorkingDirectory)'
      deploymentMethod: 'auto'