trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: python:3.9

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure-Fogo-Connection'
    appName: 'Fogolocationfunctionappdatapull'
    package: '$(System.DefaultWorkingDirectory)'
    deploymentMethod: 'auto'