trigger:
- master

pool:
  vmImage: 'windows-2019'  # This has better free tier support

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure-Fogo-Connection'
    appName: 'Fogolocationfunctionappdatapull'
    package: '$(System.DefaultWorkingDirectory)'
    deploymentMethod: 'auto'